public class testclass1{

    public testclass1(swar controller) {

    }
    public testclass1(SliderClass controller) {

    }

String s;
public Boolean a{get{return '1234'<'1236';}set;}
    public String gets() {
        s=ApexPages.currentPage().getHeaders().get('Host');
       s= s.replace('visual.force.com','');
       
        return s;
    }
    //System.assert(a,true);
    public testclass1(ApexPages.StandardController stdController) {}

public Datetime s1{get{if(s1==null) s1=System.now(); return s1;}set;}
public transient Datetime s2;
public Datetime gets2(){s2=System.now();return s2;}
}